### PR TITLE
fix compile of slurm plugin against Slurm >= 23.x

### LINKED ISSUE #152: slurm: compilation error against Slurm >= 23.x
The pdsh `slurm` module currently contains a workaround for including `slurm.h` since it exports an internal `List` interface:

https://github.com/chaos/pdsh/blob/3bc95a8d7567d9f7039dc2c16e37820dbff69e06/src/modules/slurm.c#L44-L54

Recent versions of Slurm _expanded_ this interface with additional typedefs for `struct xlist` `list_t` and `list_iterator_t` for the iterator.

This means the current workaround no longer works, since we can't let Slurm redefine our internal `List`, but we have to let them define their duplicate typedef `list_t`. Also, I noticed that the redefinition of `hostlist_t` now also causes problems, so `__hostlist_t_defined` also needs to be exported :shrug: .

The following patch seems to workaround these issues for now, though it is probably brittle in the long term. 

```diff
diff --git a/src/modules/slurm.c b/src/modules/slurm.c
index 5594c4f..c227337 100644
--- a/src/modules/slurm.c
+++ b/src/modules/slurm.c
@@ -50,6 +50,16 @@
  *  with our internal List datatype.
  */
 #define __list_datatypes_defined 1
+/*
+ * Also, Slurm>=23.x requires that `struct xlist` be typedef'd to list_t:
+ */
+typedef struct xlist list_t;
+typedef struct listIterator list_itr_t;
+/*
+ * Also, Slurm exports the hostlist_t interface as well:
+ */
+#define __hostlist_t_defined 1
+
 #include <slurm/slurm.h>
 #include <slurm/slurm_errno.h>
```

### PR DESCRIPTION
**Pull request by grondo**
This PR fixes #152 and also includes some updates to CI configuration.

### CODE REVIEW

**Review by garlick — APPROVED** [review]
LGTM!

**Comment by grondo** [comment]
Requesting approval from @ryanday36 as well.

**Comment by ryanday36** [comment]
It looks reasonable to me too. Mark Schmitz at Sandia said that he would test building with it. Don't know if you want to wait for that or not.

**Comment by ryanday36** [comment]
Mark S. says that it worked him.

**Comment by grondo** [comment]
Great, thanks @ryanday36!

**Comment by grondo** [comment]
I don't think we have mergify here, so @garlick can you press the button when you have time?

**Comment by grondo** [comment]
Thanks!

**Pull request merged**
