### PR TITLE
add msg when module cannot load due to opt conflict

### PR DESCRIPTION
**Pull request by erikja**
- A customer may have a need for both DSH and genders
- However, 2 command options conflict and so the code rejects loading one of
the two modules.
- There is no error message provided in this state, so it is hard to
know what happened. In my case I had to use gdb to step through after
some break points to see that genders was failing to load because dsh used
two if the same command line options
- This change just provides a warning in this case instead of doing it
silently.

### CODE REVIEW

**Comment by grondo** [comment]
Thanks! I _think_ this will work. I'm a little worried that this will generate errors in environments where conflicting modules may be installed (on purpose or inadvertently), where there were no errors before. However, I think this will be beneficial since then those installations could be "fixed", so this seems fine to merge.

It might be good to add a test to ensure the desired effect is achieved (and thus is not unintentionally broken in the future)

Finally, it looks like the github actions may be broken, I'll have to fix that in a separate PR.

**Comment by grondo** [comment]
Ok, if you rebase on current master, then hopefully the CI failures will be resolved.

**Comment by erikja** [comment]
I found a bug in testing after a while with the error message. The error message should reference p->opt. I used this error message to fix trouble with pdsh loading but pdcp was failing. It turned out it was because I was printing the wrong one as the problem one. I will re-test and push a different version of this. I will try re-basing as mentioned.

In an email thread, there was concern that the error message breaks function and I can understand that. However, it truly is nearly impossible to figure out which two modules conflict. It is Ok with me if it isn't accepted.

More in a bit.

**Comment by erikja** [comment]
While we use github inside HPE we use it quite differently. It appears I need to amend a commit that was 52 characters in the subject instead of 50. If it looks ok otherwise I can look at that.

Please look carefully since my first commit had a bug that was hard to spot in review. You may also not like the more verbose information. As mentioned, in an email thread, we're not sure we can handle the upstream version having error messages where it didn't before. I'm not sure what to do about that but I sure want it for our copy so I don't have to use gdb again to figure out why a module wasn't loading :) :) :). Best wishes all thank you for the advice.

**Comment by grondo** [comment]
52 characters should just be a warning. Don't worry about that

**Comment by grondo** [comment]
@erikja - I know it has been awhile, but I merged a modified version of your patch in #154. (the difference being you get the errors only with the `-d` (debug) option) Closing this PR.

**Pull request closed without merging**
