### PR TITLE
Fix pdsh build on MacOSX

### LINKED ISSUE #95: pdsh 2.32 segfault on OS X 10.11
I'm getting a segfault with the 2.32 release on OS X 10.11:
```
iMac-TMP:~ joe$ sudo lldb /usr/local/Cellar/pdsh/2.32/bin/pdsh 
Password:
(lldb) target create "/usr/local/Cellar/pdsh/2.32/bin/pdsh"
Current executable set to '/usr/local/Cellar/pdsh/2.32/bin/pdsh' (x86_64).
(lldb) r -V
Process 76749 launched: '/usr/local/Cellar/pdsh/2.32/bin/pdsh' (x86_64)
pdsh@iMac-TMP: Unable to determine ownership of pdsh binary: Bad address
Process 76749 stopped
* thread #1: tid = 0x8af88a, 0x000000010001bb92 pdsh`_next_tok(sep=",", str=0x00007fff5fbffac0) + 34 at split.c:51, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xa00000020)
    frame #0: 0x000000010001bb92 pdsh`_next_tok(sep=",", str=0x00007fff5fbffac0) + 34 at split.c:51
   48  	    int level = 0;
   49  	
   50  	    /* push str past any leading separators */
-> 51  	    while (**str != '\0' && strchr(sep, **str) != NULL)
   52  	        (*str)++;
   53  	
   54  	    if (**str == '\0')
(lldb) bt
* thread #1: tid = 0x8af88a, 0x000000010001bb92 pdsh`_next_tok(sep=",", str=0x00007fff5fbffac0) + 34 at split.c:51, queue = 'com.apple.main-thread', stop reason = EXC_BAD_ACCESS (code=1, address=0xa00000020)
  * frame #0: 0x000000010001bb92 pdsh`_next_tok(sep=",", str=0x00007fff5fbffac0) + 34 at split.c:51
    frame #1: 0x000000010001bafb pdsh`list_split(sep=",", str="") + 75 at split.c:96
    frame #2: 0x0000000100005e57 pdsh`_mod_initialize_modules_by_name(names="", m=0x0000000100800600) + 55 at mod.c:348
    frame #3: 0x0000000100005a5e pdsh`mod_load_modules(dir="/usr/local/Cellar/pdsh/2.32/lib/pdsh", opt=0x00007fff5fbffb80) + 78 at mod.c:367
    frame #4: 0x0000000100001b3c pdsh`main(argc=2, argv=0x00007fff5fbffc98) + 236 at main.c:112
    frame #5: 0x00007fff8eea35ad libdyld.dylib`start + 1
    frame #6: 0x00007fff8eea35ad libdyld.dylib`start + 1
(lldb) 
```

### PR DESCRIPTION
**Pull request by grondo**
This PR contains some fixes and cleanup for pdsh on Mac OSX.

There's still a problem building pdsh with genders support on osx, but other parts of pdsh build and are now being tested on the travis-ci osx builder.

Fixes #95

### CODE REVIEW

**Comment by grondo** [comment]
@garlick, @chu11, either of you have time to quickly review this?

**Comment by garlick** [comment]
Looks good to me.

**Comment by grondo** [comment]
@garlick, thanks for checking

**Comment by grondo** [comment]
Now someone else can push the merge button, yay!

**Pull request merged**
